import dotenv from "dotenv";
import { InferenceClient } from "@huggingface/inference";

dotenv.config();

const client = new InferenceClient(process.env.HF_API_KEY);


export async function analyzeDashboard(question, analysisData) {

  const prompt = `
You are an AI Business Analytics Assistant.

You are given analytical results generated by the application.

Use ONLY the provided analytical results to answer the user's question.

Do not invent numbers.

User Question:
${question}

Analytical Results:
${JSON.stringify(analysisData, null, 2)}

Provide a concise business answer.

If appropriate, include:

Insight:
Trend:
Recommendation:

Keep the answer easy to understand.
`;


  try {

    const response = await client.chatCompletion({

      model: "meta-llama/Llama-3.1-8B-Instruct",

      messages: [
        {
          role: "user",
          content: prompt
        }
      ],

      max_tokens: 300

    });


    return response.choices[0].message.content;

  } catch (error) {

    console.error("AI Error:", error);

    throw error;

  }

}